In [1]:
!pip install hmmlearn==0.2.7

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 129 kB 13.1 MB/s 


In [2]:
import hmmlearn
from hmmlearn import hmm
import numpy as np
import random
import itertools

In [3]:
def guitar_frets_name():
    # 開放弦から12フレット分
    frets = [
        ["E5", "F5", ["F#5", "G-5"], "G5", ["G#5", "A-5"], "A5", ["A#5", "B-5"], "B5", "C6", ["C#6", "D-6"], "D6", ["D#6", "E-6"], "E6"],
        ["B4", "C5", ["C#5", "D-5"], "D5", ["D#5", "E-5"], "E5", "F5", ["F#5", "G-5"], "G5", ["G#5", "A-5"], "A5", ["A#5", "B-5"], "B5"],
        ["G4", ["G#4", "A-4"], "A4", ["A#4", "B-4"], "B4", "C5", ["C#5", "D-5"], "D5", ["D#5", "E-5"], "E5", "F5", ["F#5", "G-5"], "G5"],
        ["D4", ["D#4", "E-4"], "E4", "F4", ["F#4", "G-4"], "G4", ["G#4", "A-4"], "A4", ["A#4", "B-4"], "B4", "C5", ["C#5", "D-5"], "D5"],
        ["A3", ["A#3", "B-3"], "B3", "C4", ["C#4", "D-4"], "D4", ["D#4", "E-4"], "E4", "F4", ["F#4", "G-4"], "G4", ["G#4", "A-4"], "A4"],
        ["E3", "F3", ["F#3", "G-3"], "G3", ["G#3", "A-3"], "A3", ["A#3", "B-3"], "B3", "C4", ["C#4", "D-4"], "D4", ["D#4", "E-4"], "E4"]
    ]
    return frets

In [4]:
def guitar_frets_dict():
    # 開放弦から20フレット分
    frets = [
        {"E5": 1, "F5": 7, "F#5":13, "G5":19, "G#5":25, "A5": 31, "A#5":37, "B5": 43, "C6": 49, "C#6": 55, "D6": 61, "D#6": 67,"E6": 73,"F6":79,"F#6":85,"G6":91,"G#6":97,"A6":103,"A#6":109,"B6":115,"C7":121},
        {"B4": 2, "C5": 8, "C#5": 14, "D5":20, "D#5":26, "E5":32, "F5": 38, "F#5":44, "G5": 50, "G#5": 56, "A5": 62, "A#5": 68,"B5": 74,"C6":80,"C#6":86,"D6":92,"D#6":98,"E6":104,"F6":110,"F#6":116,"G6":122},
        {"G4": 3, "G#4":9, "A4": 15, "A#4":21, "B4": 27, "C5":33, "C#5":39, "D5": 45, "D#5":51, "E5": 57, "F5": 63, "F#5": 69,"G5": 75,"G#5":81,"A5":87, "A#5":93,"B5":99,"C6":105,"C#6":111,"D6":117,"D#6":123},
        {"D4": 4, "D#4":10, "E4":16, "F4":22, "F#4":28, "G4": 34, "G#4":40, "A4": 46, "A#4":52, "B4": 58, "C5": 64, "C#5": 70,"D5": 76,"D#5":82,"E5":88, "F5":94,"F#5":100,"G5":106,"G#5":112,"A5":118,"A#5":124},
        {"A3": 5, "A#3":11, "B3":17, "C4":23, "C#4":29, "D4": 35, "D#4":41,"E4": 47, "F4": 53, "F#4": 59, "G4": 65, "G#4": 71,"A4": 77,"A#4":83,"B4":89, "C5":95,"C#5":101,"D5":107,"D#5":113,"E5":119,"F5":125},
        {"E3": 6, "F3": 12, "F#3":18, "G3":24, "G#3":30, "A3":36, "A#3":42,"B3": 48, "C4": 54, "C#4": 60, "D4": 66, "D#4": 72,"E4": 78,"F4":84,"F#4":90, "G4":96,"G#4":102,"A4":108,"A#4":114,"B4":120,"C5":126}
    ]
    note_number = [i for i in range(1, 127)]
    return note_number, frets

In [5]:
#(S,F)としたときにS+F = xとする． S = 弦，F = フレット ，1から126まで

observe_states, frets = guitar_frets_dict()
n_observe_states = len(observe_states)

# print(frets[1].keys())  #キーのみ出力
# print(frets[1].values())  #値のみの出力
# E4 = [d.get('E4') for d in frets]#E4の数字取得
# print(E4)



In [6]:
observes = [[23,47,22,30]] #23,47,22,30の順番の観測
n_observes = len(observes)

print(n_observe_states)

126


In [7]:
# 初期状態確率，全部同じ
startprob = []
for i in range(n_observe_states):
    startprob.append(1/n_observe_states)

startprob = np.array(startprob)
startprob

array([0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793651,
       0.00793651, 0.00793651, 0.00793651, 0.00793651, 0.00793

In [8]:
frets_items = []

#全部のキーと要素を抽出
for i in range(6):
  frets_items.append(list(frets[i].items()))

print(frets_items)

#二次元配列になっているので平坦化する
frets_items = list(itertools.chain.from_iterable(frets_items))

#番号順にソートする
frets_items = sorted(frets_items, key = lambda x:x[1])
print(frets_items)

frets_items[3][0]
# name_list[1]

[[('E5', 1), ('F5', 7), ('F#5', 13), ('G5', 19), ('G#5', 25), ('A5', 31), ('A#5', 37), ('B5', 43), ('C6', 49), ('C#6', 55), ('D6', 61), ('D#6', 67), ('E6', 73), ('F6', 79), ('F#6', 85), ('G6', 91), ('G#6', 97), ('A6', 103), ('A#6', 109), ('B6', 115), ('C7', 121)], [('B4', 2), ('C5', 8), ('C#5', 14), ('D5', 20), ('D#5', 26), ('E5', 32), ('F5', 38), ('F#5', 44), ('G5', 50), ('G#5', 56), ('A5', 62), ('A#5', 68), ('B5', 74), ('C6', 80), ('C#6', 86), ('D6', 92), ('D#6', 98), ('E6', 104), ('F6', 110), ('F#6', 116), ('G6', 122)], [('G4', 3), ('G#4', 9), ('A4', 15), ('A#4', 21), ('B4', 27), ('C5', 33), ('C#5', 39), ('D5', 45), ('D#5', 51), ('E5', 57), ('F5', 63), ('F#5', 69), ('G5', 75), ('G#5', 81), ('A5', 87), ('A#5', 93), ('B5', 99), ('C6', 105), ('C#6', 111), ('D6', 117), ('D#6', 123)], [('D4', 4), ('D#4', 10), ('E4', 16), ('F4', 22), ('F#4', 28), ('G4', 34), ('G#4', 40), ('A4', 46), ('A#4', 52), ('B4', 58), ('C5', 64), ('C#5', 70), ('D5', 76), ('D#5', 82), ('E5', 88), ('F5', 94), ('F#5', 

'D4'

In [9]:
# 出力確率
emmisionprob = []

sum_list = [0]*n_observe_states #各行の数値の合計値

#100,80,1の割り当て
for i in range(n_observe_states):
  i_key = frets_items[i][0]
  for j in range(n_observe_states):
    if i == j:#自分のキーと要素が同じなら100
      emmisionprob.append(100)
      sum_list[i] += 100

    elif frets_items[j][0] == i_key:#同じ音なら80
      emmisionprob.append(80)
      sum_list[i] += 80

    else:
      emmisionprob.append(1)
      sum_list[i] += 1

#126*126の行列にする
emmisionprob = np.array(emmisionprob).reshape(n_observe_states,n_observe_states)

#numpy配列はint型だからfloatにする
emmisionprob = emmisionprob.astype(np.float64)



#正規化
for i in range(n_observe_states):
  for j in range(n_observe_states):
    emmisionprob[i][j] = emmisionprob[i][j]/sum_list[i]

print(emmisionprob[0])

# emmisionprob[0][0]

#観測変数と潜在変数が同じ時だけ1にする．
# for i in range(n_observe_states):
#   for j in range(n_observe_states):
#       if j == i:
#         emmisionprob.append(1.0-(0.001*(n_observe_states-1)))
#       else:
#         emmisionprob.append(0.001)

# emmisionprob = np.array(emmisionprob).reshape(n_observe_states,n_observe_states)

# emmisionprob



[0.18484288 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.14787431 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.14787431 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843 0.00184843
 0.00184843 0.00184843 0.00184843 0.14787431 0.00184843 0.0018

In [10]:
# 遷移確率
transmat = []

for i in range(n_observe_states):
  for j in range(n_observe_states):
    transmat.append(1/n_observe_states)

transmat = np.array(transmat).reshape(n_observe_states,n_observe_states)
transmat

array([[0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651],
       [0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651],
       [0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651],
       ...,
       [0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651],
       [0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651],
       [0.00793651, 0.00793651, 0.00793651, ..., 0.00793651, 0.00793651,
        0.00793651]])

In [11]:
# hmmlearn のインスタンス作成
model = hmm.MultinomialHMM(n_components = n_observe_states)

model.n_features = n_observe_states #状態の数
model.startprob_= startprob #初期確率
model.transmat_= transmat #遷移確率
model.emissionprob_= emmisionprob #出力確率



In [12]:
order_node = np.array(observes).T


# 推定
logprob, decoded_codes = model.decode(order_node)
print(decoded_codes)

# print("観測:")
# for i in range(len(order_node)):
#   print()



[23 47 22 30]
